/*******
 * CreatedDate : 19-07-2018
 * Author : Amrish Surve
 * Description : Contains static values which are access in main class
 *******/

public class Cargill_BaxterUtility{

    public static string parentRecords = 'Parent';
    public static string childRecords = 'Child';
    public static string createTypeRecord = 'Month';
    public static string getObjectType = 'Account_Attachments__c';
    public static string typeDisplay = 'Display';
    public static string typeEvents = 'Events';
    public static string typeTraining = 'For Training';
    public static string typeProspectList = 'Prospect Lists and Activities';
    public static string cargillSettingTypeM = 'Month';
    public static string cargillSettingTypeY = 'Year';
}